# permalinks
permalink:           pretty

# pagination
paginate:            5

# Setup
title:               sectorzero
tagline:             'a personal log'
description:         'a personal log'
url:                 https://sectorzero.github.io
baseurl:             ''

# About/contact
author:
  name:              sectorzero
  url:               https://sectorzero.github.io
  email:             sndshd@gmail.com

# Custom vars
version:             0.0.1
