# jekyll plugins
plugins:
  - jekyll-seo-tag  # seo
  - jekyll-sitemap  # sitemap

# versioning
version:             0.0.1

# seo : site
title:               sectorzero
tagline:             'a personal log'
description:         'a personal log'
url:                 https://sectorzero.github.io
baseurl:             ''

# seo : author 
author:
  name:              sectorzero
  url:               https://sectorzero.github.io
  email:             sndshd@gmail.com

# permalinks
permalink:           pretty

# pagination
paginate:            5
